# Generated by Django 3.1.4 on 2021-02-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210222_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachfiles',
            name='path',
            field=models.FileField(upload_to='files/%Y%m%d'),
        ),
    ]
