# Generated by Django 3.1.4 on 2021-02-22 11:41

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail_path',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='thumbnail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='files/%Y%m%d'),
        ),
    ]
