# Generated by Django 3.1.4 on 2021-02-22 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210222_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyattachfiles',
            name='story_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_attach_files', to='stories.story'),
        ),
    ]
