# Generated by Django 3.1.4 on 2021-02-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210224_1457'),
        ('stories', '0002_auto_20210224_1459'),
    ]

    operations = [
    ]
