# Generated by Django 3.1.4 on 2021-02-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direct_messages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessageattachfiles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='received_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_user', to='users.user'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='send_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to='users.user'),
        ),
    ]
