# Generated by Django 3.1.4 on 2021-03-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessageattachfiles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='direct_messages.room'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.user'),
        ),
    ]
